### ISSUE TITLE
raw datasets

### ISSUE THREAD

**Issue by Scitator** [RUCAIBox/CORE#2]
Hi, 

Thanks for open-sourcing your research!
Especially for the datasets and requirements ;)
Could you please also provide a link for raw datasets download?

**Comment by hyp1231** [comment]
Hi, thanks for your interest! The raw datasets were downloaded from [Diginetica](https://competitions.codalab.org/competitions/11161), [Nowplaying](https://dbis.uibk.ac.at/node/263#nowplaying), [Retailrocket](https://www.kaggle.com/datasets/retailrocket/ecommerce-dataset), [Tmall](https://tianchi.aliyun.com/dataset/dataDetail?dataId=42) and [Yoochoose](https://www.kaggle.com/datasets/chadgostopp/recsys-challenge-2015).

If you want to preprocess the raw files with [preprocess.py](https://github.com/RUCAIBox/CORE/blob/master/dataset/preprocess.py), you may need to modify the file name and add one line as head for some of the raw files.

**Comment by Scitator** [comment]
Do you have some gdrive link to download them all with required for `preprocess.py` naming? 🙏

**Comment by hyp1231** [comment]
Hi, sorry that I cannot provide gdrive links for the original raw files due to the copyright concerns.

**Comment by Scitator** [comment]
@hyp1231 it's me again ;)

could you please check if these datasets are compatible with your preprocessing?
[dataset link #1](https://drive.google.com/drive/folders/1ritDnO_Zc6DFEU6UND9C8VCisT0ETVp5) from [Swalk repo](https://github.com/jin530/SWalk)
[dataset link #2](https://www.dropbox.com/sh/n281js5mgsvao6s/AADQbYxSFVPCun5DfwtsSxeda?dl=0) from [SLIST repo](https://github.com/jin530/SLIST)

**Comment by hyp1231** [comment]
@Scitator Yeah, I think so. I think that "rsc15" corresponds to "yoochoose" and others are just like they are. Thanks for providing the amazing links!
