### ISSUE TITLE
Confusion about the metric P(Precision) and R(Recall)

### ISSUE THREAD

**Issue by Jaccelerator** [RUCAIBox/CORE#6]
Hi, author! I have learned a lot, but still confused about the metric.
In the session recommendation domain, many previous works (such as SR-GNN) use the metric P to measure the proportion user desired items among the top-K score items in test dataset. Why some recent work (including yours) call it R? 
From my view, top-K is the prediction result, and that as denominator (TP + FP) according the basic idea of classification task.  Thanks!

**Comment by hyp1231** [comment]
Hi, thanks for your interest!

Let's take @50 metrics as one example.
* For Precision@50, if we successfully retrieve the ground-truth item for one session, we have TP=1, TP+FP=50, and the precision is 1/50=0.02.
* For Recall@50, if we successfully retrieve the ground-truth item for one session, we have TP=1, TP+FN=1, and the recall is 1.

In [SR-GNN's implementation](https://github.com/CRIPAC-DIG/SR-GNN/blob/master/pytorch_code/model.py#L150), I believe it's the same as Recall@K. For CORE's implementation, we also use Recall@K.

But actually, as we have analyzed, Recall@50 is just 50 * Precision@50. We can use whatever we like to evaluate, these two metrics just have the same trends for session-based recommendation using leave-last-out splits.

**Comment by Jaccelerator** [comment]
I got it, thanks very much!

**Comment by Jaccelerator** [comment]
By the way, could you kindly introduce how the metric is calculated in your repo (maybe it in RecBole)?

**Comment by hyp1231** [comment]
> By the way, could you kindly introduce how the metric is calculated in your repo (maybe it in RecBole)?

Yes they are integrated in RecBole. Please refer to [https://recbole.io/docs/recbole/recbole.evaluator.metrics.html](https://recbole.io/docs/recbole/recbole.evaluator.metrics.html).
